events {}

# Site principal sur le port 8080
http {
    server {
      listen 8080;
      server_name localhost;
      client_max_body_size 10g;

      error_page 404 /errors/404.html;
      error_page 500 /errors/500.html;

      location / {
        root            /var/www/html;
        index           index.html;
        autoindex       off;
      }

      location /api {
        root            /var/www/api;
        autoindex       off;
		return          300;
      }

      location /upload {
        root            /var/www;
      }

      location /files {
        root            /var/www/shared;
        autoindex       on;
      }

      location /old-page {
        return 301 /new-page;
      }

      location /cgi-bin {
        root            /var/www/cgi-bin;
      }
    }

    # Deuxième serveur sur port 8081
    server {
      listen 8081;
      client_max_body_size 1m;

      location / {
        root            /var/www/site2;
        index           index.html;
        autoindex       off;
      }
    }
}