server {
	listen 8080;

	server_name demo;

	client_max_body_size 10m;

	root www;

	location / {
		root            www;
		index           index.html;
		autoindex       off;
		allowed_methods GET;
	}

	location /files {
		root            www;
		autoindex       on;
	}

	location /upload {
		root            www;
		allowed_methods POST DELETE GET;
		upload_store    ./www/upload;
		autoindex       on;
	}

	location /cgi-bin {
		root            www;
		cgi_pass        .py /usr/bin/python3;
	}

	location /old-page {
		return 301 /index.html;
	}
}
