server {
	listen 8080;

	server_name test;

	client_max_body_size 1m;

	root www;

	location / {
		root            www;
		autoindex       on;
		allowed_methods GET;
	}

	location /post_body {
		root            www;
		allowed_methods POST;
		client_max_body_size 100;
	}

	location /directory {
		root            www;
		client_max_body_size 1g;
		allowed_methods GET POST;
		autoindex       off;
		index           youpi.bad_extension;
		cgi_pass        .bla /home/antares/Documents/webserv_boost/www/cgi-bin/cgi_test;
	}
}
